### PR TITLE
Add support for laravel 8

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by aceraven777** [comment]
@lloricode Merged it. Thanks

**Comment by lloricode** [comment]
@aceraven777 can you tag this update?

**Comment by aceraven777** [comment]
@lloricode Ops. Sorry. I forgot to create a tag/release for this.

https://github.com/aceraven777/laravel-paymaya/releases/tag/v1.0.10

**Comment by lloricode** [comment]
@aceraven777 thank you

**Pull request merged**
